# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: Deploy to AWS

on:
  push:

env:
  IMAGE_PATH_AND_TAG: ghcr.io/application-repository:release-1.0
  AWS_DEFAULT_REGION: 'us-east-1' 
  PORT: 3838
  COST_CENTER: "NO PROGRAM / 000000"
  STACK_NAME_PREFIX: application-repository
  CONTAINER_ENV: example
 

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
        # Authenticate to AWS using GitHub OIDC
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::<account-number>:role/<role-name>
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 1200
          
        # https://github.com/marketplace/actions/aws-cdk-github-actions
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          working_dir: 'cdk'
        env:
          DOCKER_IMAGE: ${{ env.IMAGE_PATH_AND_TAG }}
 
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          working_dir: 'cdk'
          actions_comment: false
        env:
          DOCKER_IMAGE: ${{ env.IMAGE_PATH_AND_TAG }}
           